name: dopamine_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=18.0
  - python=3.6
  - pip:
    - graphviz
    - hdf5
    - h5py
    - keras
    - numpy
    - pydot
    - python-graphviz
    - tensorflow-gpu

