name: keras
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - hdf5
  - h5py
  - numpy
  - matplotlib
  - pip=18.0
  - pydot
  - python=3.6
  - python-graphviz
  - scipy
  - pip:
    - keras
    - tf-nightly-gpu

